// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1-devel
// 	protoc        v3.6.1
// source: tgams.proto

package _go

import (
	context "context"
	grpc "google.golang.org/grpc"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PingResponse_PingStatus int32

const (
	PingResponse_OK       PingResponse_PingStatus = 0
	PingResponse_STARTING PingResponse_PingStatus = 1
	PingResponse_STOPPING PingResponse_PingStatus = 2
	PingResponse_READY    PingResponse_PingStatus = 3
	PingResponse_BUSY     PingResponse_PingStatus = 4
	PingResponse_ERROR    PingResponse_PingStatus = 5
)

// Enum value maps for PingResponse_PingStatus.
var (
	PingResponse_PingStatus_name = map[int32]string{
		0: "OK",
		1: "STARTING",
		2: "STOPPING",
		3: "READY",
		4: "BUSY",
		5: "ERROR",
	}
	PingResponse_PingStatus_value = map[string]int32{
		"OK":       0,
		"STARTING": 1,
		"STOPPING": 2,
		"READY":    3,
		"BUSY":     4,
		"ERROR":    5,
	}
)

func (x PingResponse_PingStatus) Enum() *PingResponse_PingStatus {
	p := new(PingResponse_PingStatus)
	*p = x
	return p
}

func (x PingResponse_PingStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PingResponse_PingStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_tgams_proto_enumTypes[0].Descriptor()
}

func (PingResponse_PingStatus) Type() protoreflect.EnumType {
	return &file_tgams_proto_enumTypes[0]
}

func (x PingResponse_PingStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PingResponse_PingStatus.Descriptor instead.
func (PingResponse_PingStatus) EnumDescriptor() ([]byte, []int) {
	return file_tgams_proto_rawDescGZIP(), []int{1, 0}
}

type PingRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RequestId uint64 `protobuf:"varint,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
}

func (x *PingRequest) Reset() {
	*x = PingRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tgams_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRequest) ProtoMessage() {}

func (x *PingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tgams_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRequest.ProtoReflect.Descriptor instead.
func (*PingRequest) Descriptor() ([]byte, []int) {
	return file_tgams_proto_rawDescGZIP(), []int{0}
}

func (x *PingRequest) GetRequestId() uint64 {
	if x != nil {
		return x.RequestId
	}
	return 0
}

type PingResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ResponseId uint64                  `protobuf:"varint,1,opt,name=response_id,json=responseId,proto3" json:"response_id,omitempty"`
	RequestId  uint64                  `protobuf:"varint,2,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Status     PingResponse_PingStatus `protobuf:"varint,3,opt,name=status,proto3,enum=PingResponse_PingStatus" json:"status,omitempty"`
}

func (x *PingResponse) Reset() {
	*x = PingResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tgams_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingResponse) ProtoMessage() {}

func (x *PingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tgams_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingResponse.ProtoReflect.Descriptor instead.
func (*PingResponse) Descriptor() ([]byte, []int) {
	return file_tgams_proto_rawDescGZIP(), []int{1}
}

func (x *PingResponse) GetResponseId() uint64 {
	if x != nil {
		return x.ResponseId
	}
	return 0
}

func (x *PingResponse) GetRequestId() uint64 {
	if x != nil {
		return x.RequestId
	}
	return 0
}

func (x *PingResponse) GetStatus() PingResponse_PingStatus {
	if x != nil {
		return x.Status
	}
	return PingResponse_OK
}

type TimeSyncRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RequestId uint64 `protobuf:"varint,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	T1        int64  `protobuf:"varint,2,opt,name=t1,proto3" json:"t1,omitempty"`
}

func (x *TimeSyncRequest) Reset() {
	*x = TimeSyncRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tgams_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TimeSyncRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimeSyncRequest) ProtoMessage() {}

func (x *TimeSyncRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tgams_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimeSyncRequest.ProtoReflect.Descriptor instead.
func (*TimeSyncRequest) Descriptor() ([]byte, []int) {
	return file_tgams_proto_rawDescGZIP(), []int{2}
}

func (x *TimeSyncRequest) GetRequestId() uint64 {
	if x != nil {
		return x.RequestId
	}
	return 0
}

func (x *TimeSyncRequest) GetT1() int64 {
	if x != nil {
		return x.T1
	}
	return 0
}

type TimeSyncResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ResponseId uint64 `protobuf:"varint,1,opt,name=response_id,json=responseId,proto3" json:"response_id,omitempty"`
	RequestId  uint64 `protobuf:"varint,2,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	T1         int64  `protobuf:"varint,10,opt,name=t1,proto3" json:"t1,omitempty"`
	T2         int64  `protobuf:"varint,11,opt,name=t2,proto3" json:"t2,omitempty"`
	T3         int64  `protobuf:"varint,12,opt,name=t3,proto3" json:"t3,omitempty"`
	T4         int64  `protobuf:"varint,13,opt,name=t4,proto3" json:"t4,omitempty"`
}

func (x *TimeSyncResponse) Reset() {
	*x = TimeSyncResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tgams_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TimeSyncResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimeSyncResponse) ProtoMessage() {}

func (x *TimeSyncResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tgams_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimeSyncResponse.ProtoReflect.Descriptor instead.
func (*TimeSyncResponse) Descriptor() ([]byte, []int) {
	return file_tgams_proto_rawDescGZIP(), []int{3}
}

func (x *TimeSyncResponse) GetResponseId() uint64 {
	if x != nil {
		return x.ResponseId
	}
	return 0
}

func (x *TimeSyncResponse) GetRequestId() uint64 {
	if x != nil {
		return x.RequestId
	}
	return 0
}

func (x *TimeSyncResponse) GetT1() int64 {
	if x != nil {
		return x.T1
	}
	return 0
}

func (x *TimeSyncResponse) GetT2() int64 {
	if x != nil {
		return x.T2
	}
	return 0
}

func (x *TimeSyncResponse) GetT3() int64 {
	if x != nil {
		return x.T3
	}
	return 0
}

func (x *TimeSyncResponse) GetT4() int64 {
	if x != nil {
		return x.T4
	}
	return 0
}

var File_tgams_proto protoreflect.FileDescriptor

var file_tgams_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x74, 0x67, 0x61, 0x6d, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x2c, 0x0a,
	0x0b, 0x50, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1d, 0x0a, 0x0a,
	0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04,
	0x52, 0x09, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x49, 0x64, 0x22, 0xd2, 0x01, 0x0a, 0x0c,
	0x50, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1f, 0x0a, 0x0b,
	0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x04, 0x52, 0x0a, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x49, 0x64, 0x12, 0x1d, 0x0a,
	0x0a, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x04, 0x52, 0x09, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x49, 0x64, 0x12, 0x30, 0x0a, 0x06,
	0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x18, 0x2e, 0x50,
	0x69, 0x6e, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x50, 0x69, 0x6e, 0x67,
	0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x50,
	0x0a, 0x0a, 0x50, 0x69, 0x6e, 0x67, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x06, 0x0a, 0x02,
	0x4f, 0x4b, 0x10, 0x00, 0x12, 0x0c, 0x0a, 0x08, 0x53, 0x54, 0x41, 0x52, 0x54, 0x49, 0x4e, 0x47,
	0x10, 0x01, 0x12, 0x0c, 0x0a, 0x08, 0x53, 0x54, 0x4f, 0x50, 0x50, 0x49, 0x4e, 0x47, 0x10, 0x02,
	0x12, 0x09, 0x0a, 0x05, 0x52, 0x45, 0x41, 0x44, 0x59, 0x10, 0x03, 0x12, 0x08, 0x0a, 0x04, 0x42,
	0x55, 0x53, 0x59, 0x10, 0x04, 0x12, 0x09, 0x0a, 0x05, 0x45, 0x52, 0x52, 0x4f, 0x52, 0x10, 0x05,
	0x22, 0x40, 0x0a, 0x0f, 0x54, 0x69, 0x6d, 0x65, 0x53, 0x79, 0x6e, 0x63, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x5f, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x09, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x49, 0x64, 0x12, 0x0e, 0x0a, 0x02, 0x74, 0x31, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02,
	0x74, 0x31, 0x22, 0x92, 0x01, 0x0a, 0x10, 0x54, 0x69, 0x6d, 0x65, 0x53, 0x79, 0x6e, 0x63, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x72, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0a, 0x72, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x49, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x72, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x09, 0x72, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x49, 0x64, 0x12, 0x0e, 0x0a, 0x02, 0x74, 0x31, 0x18, 0x0a, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x02, 0x74, 0x31, 0x12, 0x0e, 0x0a, 0x02, 0x74, 0x32, 0x18, 0x0b, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x02, 0x74, 0x32, 0x12, 0x0e, 0x0a, 0x02, 0x74, 0x33, 0x18, 0x0c, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x02, 0x74, 0x33, 0x12, 0x0e, 0x0a, 0x02, 0x74, 0x34, 0x18, 0x0d, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x02, 0x74, 0x34, 0x32, 0x10, 0x0a, 0x0e, 0x43, 0x6f, 0x6e, 0x74, 0x72,
	0x6f, 0x6c, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x32, 0x12, 0x0a, 0x10, 0x54, 0x65, 0x6c,
	0x65, 0x6d, 0x65, 0x74, 0x72, 0x79, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x42, 0x35, 0x5a,
	0x20, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x42, 0x47, 0x72, 0x65,
	0x77, 0x65, 0x6c, 0x6c, 0x2f, 0x74, 0x67, 0x61, 0x6d, 0x73, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x67,
	0x6f, 0xaa, 0x02, 0x10, 0x42, 0x65, 0x6e, 0x47, 0x72, 0x65, 0x77, 0x65, 0x6c, 0x6c, 0x2e, 0x54,
	0x67, 0x61, 0x6d, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_tgams_proto_rawDescOnce sync.Once
	file_tgams_proto_rawDescData = file_tgams_proto_rawDesc
)

func file_tgams_proto_rawDescGZIP() []byte {
	file_tgams_proto_rawDescOnce.Do(func() {
		file_tgams_proto_rawDescData = protoimpl.X.CompressGZIP(file_tgams_proto_rawDescData)
	})
	return file_tgams_proto_rawDescData
}

var file_tgams_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_tgams_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_tgams_proto_goTypes = []interface{}{
	(PingResponse_PingStatus)(0), // 0: PingResponse.PingStatus
	(*PingRequest)(nil),          // 1: PingRequest
	(*PingResponse)(nil),         // 2: PingResponse
	(*TimeSyncRequest)(nil),      // 3: TimeSyncRequest
	(*TimeSyncResponse)(nil),     // 4: TimeSyncResponse
}
var file_tgams_proto_depIdxs = []int32{
	0, // 0: PingResponse.status:type_name -> PingResponse.PingStatus
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_tgams_proto_init() }
func file_tgams_proto_init() {
	if File_tgams_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_tgams_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PingRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tgams_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PingResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tgams_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TimeSyncRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tgams_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TimeSyncResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_tgams_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_tgams_proto_goTypes,
		DependencyIndexes: file_tgams_proto_depIdxs,
		EnumInfos:         file_tgams_proto_enumTypes,
		MessageInfos:      file_tgams_proto_msgTypes,
	}.Build()
	File_tgams_proto = out.File
	file_tgams_proto_rawDesc = nil
	file_tgams_proto_goTypes = nil
	file_tgams_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// ControlChannelClient is the client API for ControlChannel service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ControlChannelClient interface {
}

type controlChannelClient struct {
	cc grpc.ClientConnInterface
}

func NewControlChannelClient(cc grpc.ClientConnInterface) ControlChannelClient {
	return &controlChannelClient{cc}
}

// ControlChannelServer is the server API for ControlChannel service.
type ControlChannelServer interface {
}

// UnimplementedControlChannelServer can be embedded to have forward compatible implementations.
type UnimplementedControlChannelServer struct {
}

func RegisterControlChannelServer(s *grpc.Server, srv ControlChannelServer) {
	s.RegisterService(&_ControlChannel_serviceDesc, srv)
}

var _ControlChannel_serviceDesc = grpc.ServiceDesc{
	ServiceName: "ControlChannel",
	HandlerType: (*ControlChannelServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams:     []grpc.StreamDesc{},
	Metadata:    "tgams.proto",
}

// TelemetryChannelClient is the client API for TelemetryChannel service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type TelemetryChannelClient interface {
}

type telemetryChannelClient struct {
	cc grpc.ClientConnInterface
}

func NewTelemetryChannelClient(cc grpc.ClientConnInterface) TelemetryChannelClient {
	return &telemetryChannelClient{cc}
}

// TelemetryChannelServer is the server API for TelemetryChannel service.
type TelemetryChannelServer interface {
}

// UnimplementedTelemetryChannelServer can be embedded to have forward compatible implementations.
type UnimplementedTelemetryChannelServer struct {
}

func RegisterTelemetryChannelServer(s *grpc.Server, srv TelemetryChannelServer) {
	s.RegisterService(&_TelemetryChannel_serviceDesc, srv)
}

var _TelemetryChannel_serviceDesc = grpc.ServiceDesc{
	ServiceName: "TelemetryChannel",
	HandlerType: (*TelemetryChannelServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams:     []grpc.StreamDesc{},
	Metadata:    "tgams.proto",
}
