# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tgams.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='tgams.proto',
  package='',
  syntax='proto3',
  serialized_options=b'Z github.com/BGrewell/tgams/api/go\252\002\020BenGrewell.Tgams',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0btgams.proto\"!\n\x0bPingRequest\x12\x12\n\nrequest_id\x18\x01 \x01(\x04\"\xb3\x01\n\x0cPingResponse\x12\x13\n\x0bresponse_id\x18\x01 \x01(\x04\x12\x12\n\nrequest_id\x18\x02 \x01(\x04\x12(\n\x06status\x18\x03 \x01(\x0e\x32\x18.PingResponse.PingStatus\"P\n\nPingStatus\x12\x06\n\x02OK\x10\x00\x12\x0c\n\x08STARTING\x10\x01\x12\x0c\n\x08STOPPING\x10\x02\x12\t\n\x05READY\x10\x03\x12\x08\n\x04\x42USY\x10\x04\x12\t\n\x05\x45RROR\x10\x05\"1\n\x0fTimeSyncRequest\x12\x12\n\nrequest_id\x18\x01 \x01(\x04\x12\n\n\x02t1\x18\x02 \x01(\x03\"k\n\x10TimeSyncResponse\x12\x13\n\x0bresponse_id\x18\x01 \x01(\x04\x12\x12\n\nrequest_id\x18\x02 \x01(\x04\x12\n\n\x02t1\x18\n \x01(\x03\x12\n\n\x02t2\x18\x0b \x01(\x03\x12\n\n\x02t3\x18\x0c \x01(\x03\x12\n\n\x02t4\x18\r \x01(\x03\x32\x10\n\x0e\x43ontrolChannel2\x12\n\x10TelemetryChannelB5Z github.com/BGrewell/tgams/api/go\xaa\x02\x10\x42\x65nGrewell.Tgamsb\x06proto3'
)



_PINGRESPONSE_PINGSTATUS = _descriptor.EnumDescriptor(
  name='PingStatus',
  full_name='PingResponse.PingStatus',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='OK', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='STARTING', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='STOPPING', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='READY', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='BUSY', index=4, number=4,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='ERROR', index=5, number=5,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=150,
  serialized_end=230,
)
_sym_db.RegisterEnumDescriptor(_PINGRESPONSE_PINGSTATUS)


_PINGREQUEST = _descriptor.Descriptor(
  name='PingRequest',
  full_name='PingRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='request_id', full_name='PingRequest.request_id', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=15,
  serialized_end=48,
)


_PINGRESPONSE = _descriptor.Descriptor(
  name='PingResponse',
  full_name='PingResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='response_id', full_name='PingResponse.response_id', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='request_id', full_name='PingResponse.request_id', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='status', full_name='PingResponse.status', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _PINGRESPONSE_PINGSTATUS,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=51,
  serialized_end=230,
)


_TIMESYNCREQUEST = _descriptor.Descriptor(
  name='TimeSyncRequest',
  full_name='TimeSyncRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='request_id', full_name='TimeSyncRequest.request_id', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='t1', full_name='TimeSyncRequest.t1', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=232,
  serialized_end=281,
)


_TIMESYNCRESPONSE = _descriptor.Descriptor(
  name='TimeSyncResponse',
  full_name='TimeSyncResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='response_id', full_name='TimeSyncResponse.response_id', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='request_id', full_name='TimeSyncResponse.request_id', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='t1', full_name='TimeSyncResponse.t1', index=2,
      number=10, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='t2', full_name='TimeSyncResponse.t2', index=3,
      number=11, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='t3', full_name='TimeSyncResponse.t3', index=4,
      number=12, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='t4', full_name='TimeSyncResponse.t4', index=5,
      number=13, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=283,
  serialized_end=390,
)

_PINGRESPONSE.fields_by_name['status'].enum_type = _PINGRESPONSE_PINGSTATUS
_PINGRESPONSE_PINGSTATUS.containing_type = _PINGRESPONSE
DESCRIPTOR.message_types_by_name['PingRequest'] = _PINGREQUEST
DESCRIPTOR.message_types_by_name['PingResponse'] = _PINGRESPONSE
DESCRIPTOR.message_types_by_name['TimeSyncRequest'] = _TIMESYNCREQUEST
DESCRIPTOR.message_types_by_name['TimeSyncResponse'] = _TIMESYNCRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PingRequest = _reflection.GeneratedProtocolMessageType('PingRequest', (_message.Message,), {
  'DESCRIPTOR' : _PINGREQUEST,
  '__module__' : 'tgams_pb2'
  # @@protoc_insertion_point(class_scope:PingRequest)
  })
_sym_db.RegisterMessage(PingRequest)

PingResponse = _reflection.GeneratedProtocolMessageType('PingResponse', (_message.Message,), {
  'DESCRIPTOR' : _PINGRESPONSE,
  '__module__' : 'tgams_pb2'
  # @@protoc_insertion_point(class_scope:PingResponse)
  })
_sym_db.RegisterMessage(PingResponse)

TimeSyncRequest = _reflection.GeneratedProtocolMessageType('TimeSyncRequest', (_message.Message,), {
  'DESCRIPTOR' : _TIMESYNCREQUEST,
  '__module__' : 'tgams_pb2'
  # @@protoc_insertion_point(class_scope:TimeSyncRequest)
  })
_sym_db.RegisterMessage(TimeSyncRequest)

TimeSyncResponse = _reflection.GeneratedProtocolMessageType('TimeSyncResponse', (_message.Message,), {
  'DESCRIPTOR' : _TIMESYNCRESPONSE,
  '__module__' : 'tgams_pb2'
  # @@protoc_insertion_point(class_scope:TimeSyncResponse)
  })
_sym_db.RegisterMessage(TimeSyncResponse)


DESCRIPTOR._options = None

_CONTROLCHANNEL = _descriptor.ServiceDescriptor(
  name='ControlChannel',
  full_name='ControlChannel',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=392,
  serialized_end=408,
  methods=[
])
_sym_db.RegisterServiceDescriptor(_CONTROLCHANNEL)

DESCRIPTOR.services_by_name['ControlChannel'] = _CONTROLCHANNEL


_TELEMETRYCHANNEL = _descriptor.ServiceDescriptor(
  name='TelemetryChannel',
  full_name='TelemetryChannel',
  file=DESCRIPTOR,
  index=1,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=410,
  serialized_end=428,
  methods=[
])
_sym_db.RegisterServiceDescriptor(_TELEMETRYCHANNEL)

DESCRIPTOR.services_by_name['TelemetryChannel'] = _TELEMETRYCHANNEL

# @@protoc_insertion_point(module_scope)
